/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_EE1520SERVER_H_
#define JSONRPC_CPP_STUB_EE1520SERVER_H_

#include <jsonrpccpp/server.h>

class ee1520Server : public jsonrpc::AbstractServer<ee1520Server>
{
    public:
        ee1520Server(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<ee1520Server>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("update", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "updating_json",jsonrpc::JSON_STRING, NULL), &ee1520Server::updateI);
            this->bindAndAddMethod(jsonrpc::Procedure("search", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "search_clause",jsonrpc::JSON_STRING, NULL), &ee1520Server::searchI);
            this->bindAndAddMethod(jsonrpc::Procedure("upload", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "updating_json",jsonrpc::JSON_OBJECT, NULL), &ee1520Server::uploadI);
            this->bindAndAddMethod(jsonrpc::Procedure("question", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "question_json",jsonrpc::JSON_OBJECT, NULL), &ee1520Server::questionI);
            this->bindAndAddMethod(jsonrpc::Procedure("dump2json", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "identity",jsonrpc::JSON_STRING, NULL), &ee1520Server::dump2jsonI);
        }

        inline virtual void updateI(const Json::Value &request, Json::Value &response)
        {
            response = this->update(request["updating_json"].asString());
        }
        inline virtual void searchI(const Json::Value &request, Json::Value &response)
        {
            response = this->search(request["search_clause"].asString());
        }
        inline virtual void uploadI(const Json::Value &request, Json::Value &response)
        {
            response = this->upload(request["updating_json"]);
        }
        inline virtual void questionI(const Json::Value &request, Json::Value &response)
        {
            response = this->question(request["question_json"]);
        }
        inline virtual void dump2jsonI(const Json::Value &request, Json::Value &response)
        {
            response = this->dump2json(request["identity"].asString());
        }
        virtual Json::Value update(const std::string& updating_json) = 0;
        virtual Json::Value search(const std::string& search_clause) = 0;
        virtual Json::Value upload(const Json::Value& updating_json) = 0;
        virtual Json::Value question(const Json::Value& question_json) = 0;
        virtual Json::Value dump2json(const std::string& identity) = 0;
};

#endif //JSONRPC_CPP_STUB_EE1520SERVER_H_
